// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rudmenhlysyxxcgvncnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1ZG1lbmhseXN5eHhjZ3ZuY252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzOTIzNDQsImV4cCI6MjA2NTk2ODM0NH0.J-o3bczcKAwTg5qEPpMIT6S-qFR8lo5NmHFe0YiTirE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);